packages:
  - 'packages/*'
  - 'packages/routing-sdk/**'
  - 'apps/*'
  - 'apis/*'
  - 'examples/*'
  - 'scripts'

catalog:
  viem: ^2.21.53
  wagmi: ^2.14.9
  next: 14.2.14
  wrangler: 3.81.0
  '@aptos-labs/ts-sdk': 1.30.0
